name: Commit Bracket
on:
  schedule:
    - cron: '42 3 10 4 *'

jobs:
  commit-bracket:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: jwmickey/circle-bracket
      - name: update-season
        run: |
          npm install
          npm run fetch-bracket
          npm run validate-bracket
      - name: create-pr
        uses: peter-evans/create-pull-request@v7
        with:
          title: Automatic bracket persist for current season
          branch: auto-save-season
          labels: auto-pr
          delete-branch: true
          add-paths: seasons/bracket-*.json
      - name: auto-merge
        run: gh pr merge --merge --auto auto-save-season
        env:
          GH_TOKEN: ${{ github.token }}