name: Commit Bracket
on: push
#  schedule:
#    # Tourney is for sure over by April 30th
#    - cron:  '0 0 30 4 0'

jobs:
  commit-bracket:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: jwmickey/circle-bracket
      - name: update-season
        run: |
          npm ci
          npm run fetch-bracket 2024
          npm run validate-bracket 2024
      - name: create-pr
        uses: peter-evans/create-pull-request@v7
        with:
          title: Automatic bracket persist for current season
          branch: auto-bracket-persist
          labels: auto-pr
          delete-branch: true
      - name: auto-merge
        run: gh pr merge --merge --auto "1"
        env:
          GH_TOKEN: ${{ github.token }}