name: Update Live Bracket
on:
  schedule:
    - cron: '*/30 * 14-31 3 *'
    - cron: '*/30 * 01-13 4 *'
jobs:
  update:
    name: Request Update Function
    runs-on: ubuntu-latest
    steps:
      - name: Curl Request
        run: curl -X GET https://circlebracket.netlify.app/.netlify/functions/update-live-bracket
