name: Update Live Bracket
on:
  schedule:
    - cron: '*/15 0-1,14-23 * 3,4 2,3,4,5,6,0'
jobs:
  update:
    name: Request Update Function
    runs-on: ubuntu-latest
    steps:
      - name: Curl Request
        run: curl -X GET https://circlebracket.netlify.app/.netlify/functions/update-live-bracket
